upgrading to 0.6.22 from upstream (#1)
* Merge pull request #16198 from open-webui/dependabot/pip/backend/dev/markdown-3.8.2

chore(deps): bump markdown from 3.7 to 3.8.2 in /backend

* Merge pull request #16197 from open-webui/dependabot/pip/backend/dev/authlib-1.6.1

chore(deps): bump authlib from 1.4.1 to 1.6.1 in /backend

* Merge pull request #16194 from ahangarha/patch-1

i18n:update fa translation

* Merge branch 'dev' into feat/otel-logger-handler

* Merge pull request #16192 from expruc/feat/otel-logger-handler

feat: otel logger handler

* UserMenu: Fix quote typo in docs link.

* Docs link in the user menu are invalid when clicked via browser.

Signed-off-by: Hadad <hadad@linuxmail.org>

* fix: add conditional password confirmation on signup

Password confirmation during signup is now only enforced if the 'enable_signup_password_confirmation' feature flag is enabled in the config. This allows for more flexible signup flows based on configuration.

* Merge pull request #16233 from andrewbbaek/dev

fix: add conditional password confirmation on signup

* Merge pull request #16231 from hadadarjt/dev

UserMenu: Fix quote typo in docs link.

* refac/fix: tool payload

* added otel lgos specific config

* Merge pull request #16237 from expruc/chore/separate_otel_logs_config

chore: separate otel logs config

* feat: Add password visibility toggle to password fields w SensitiveInput.svelte component

* fix(frontend): Attempt to resolve TypeError in RichTextInput.svelte

Fixes an issue where `ue.getWordAtDocPos is not a function` would be thrown in `MessageInput.svelte`.

The error was caused by a timing issue where the `getWordAtDocPos` method on the `RichTextInput` component was not available when called from an event handler within the same component.

This change refactors the code to pass the `getWordAtDocPos` function as a callback prop from `RichTextInput` to `MessageInput`, ensuring it's available when needed.

* Merge pull request #16246 from silentoplayz/sensitiveinput-password-fields

feat: Add password visibility toggle to password fields with SensitiveInput.svelte component

* enh/refac: redis cluster support

* Merge pull request #16033 from silentoplayz/sticky-search

refac: sticky headers & smarter pagination on users list page

* refac: styling

* refac

* enh: include chat id in feedback modal

* Merge pull request #15903 from Hisma/marker-api-update

feat: Add configurable API URL (for self-hosting) and additional_config parameter for Datalab Marker API

* refac

* refac

* refac/fix: folder direct file upload

* fix: styling

* revert: Reverts requested

* refac/fix: table markdown input

* refac

* Merge pull request #16249 from silentoplayz/fix-richtext-getwordatdocpos

fix(frontend): Attempt to resolve TypeError in RichTextInput.svelte

* enh: ability to sort folder chats

* Merge pull request #15705 from rgaricano/dev-HybridSearch-bm25_slider

FEAT: STYLE: Frontend HybridSearch-BM25 Slider

* refac: styling

* Merge pull request #15640 from ipapapa/feat/cleaner-logs

refactor(logger): Conditionally include extra_json in logs

* Merge pull request #16009 from Classic298/patch-1

feat: add OAuth configuration warning for missing OPENID_PROVIDER_URL

* add oracledb only

>      "moto[s3]>=5.0.26",
-
+    "oracledb>=3.2.0",

* add custom cors scheme option

* translate elements in banner for accessibility

* aria hidden on svgs to hide them from assistive tech

* Fix syntax error where the previous use of :metadata::text in some sqlachamy/postgres versions doesn't bind at all

Fix syntax error where the previous use of :metadata::text in some sqlachamy/postgres versions doesn't bind the variable at all

* Merge pull request #16296 from itk-dev/feature/accessible-banner

feat: translate elements in banner for accessibility

* Merge pull request #16295 from Jakobu5/cors-custom-scheme-patch

feat: add custom cors scheme option

* refac: styling

* fix: chat metadata wasn't being taken into consideration when cloning a chat

fix: chat metadata wasn't being taken into consideration when cloning a chat

* refac: has_users

Co-Authored-By: pickle-dice <159401444+hassan-ajek@users.noreply.github.com>

* refac: styling

* enh: abililty to stop merge response

* chore: analytics scaffolding

* fix: cloned chat metadata not taken into consideration

* feat: ENABLE_ADMIN_WORKSPACE_CONTENT_ACCESS

Co-Authored-By: Classic298 <27028174+Classic298@users.noreply.github.com>

* Set av==14.0.1